"""added updated_by column in member table

Revision ID: 24038fcb30c9
Revises: b11981b3cf9e
Create Date: 2026-03-12 20:38:30.348062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24038fcb30c9'
down_revision: Union[str, Sequence[str], None] = 'b11981b3cf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Members', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Members', 'updated_by')
    # ### end Alembic commands ###
