"""added isDeleted column and modelbase

Revision ID: 890b317146bb
Revises: 
Create Date: 2026-03-11 19:06:03.499025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890b317146bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admins', sa.Column('isDeleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('Logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('Logs', sa.Column('isDeleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('Members', sa.Column('isDeleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('Owners', sa.Column('isDeleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('Sessions', sa.Column('added_at', sa.DateTime(), nullable=False))
    op.add_column('Sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('Sessions', sa.Column('isDeleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sessions', 'isDeleted')
    op.drop_column('Sessions', 'updated_at')
    op.drop_column('Sessions', 'added_at')
    op.drop_column('Owners', 'isDeleted')
    op.drop_column('Members', 'isDeleted')
    op.drop_column('Logs', 'isDeleted')
    op.drop_column('Logs', 'updated_at')
    op.drop_column('Admins', 'isDeleted')
    # ### end Alembic commands ###
