"""removed paid_at and recorded_at

Revision ID: b11981b3cf9e
Revises: 890b317146bb
Create Date: 2026-03-12 18:42:27.536751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b11981b3cf9e'
down_revision: Union[str, Sequence[str], None] = '890b317146bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Payments', 'paid_at')
    op.drop_column('Sessions', 'recorded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sessions', sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Payments', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
